
// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { Londrina_Solid } from "next/font/google";
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import Web3ModalProvider from '@/context'

const londrina = Londrina_Solid({ subsets: ["latin"], variable: '--font-londrina',
	weight: "400", display: "swap" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={londrina.className}>
        <Web3ModalProvider initialState={initialState}>{children}</Web3ModalProvider>
      </body>
    </html>
  )
}
